# Generated by Django 5.1.1 on 2024-10-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_mymodel_name_mymodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
