# Generated by Django 5.1.1 on 2024-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_mymodel_description_alter_mymodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
